### ISSUE TITLE
Can I use Julia 1.1 with the code now?

### ISSUE THREAD

**Issue by Wei-TianHao** [sisl/ngsim_env#11]
Hi,

I tried to install ngsim_env with Julia 0.7 on Mac. Met a lot of problems. Will it be easier to install with Julia 1.1? Is the 0.7fixes branch working now?

**Comment by Wei-TianHao** [comment]
In the instruction, at the end of Install ngsim_env part:

>  Add the local AutoEnvs module to our julia environment
>   ] dev ~/ngsim_env/julia

I guess "] dev" is a typo?

**Comment by Wei-TianHao** [comment]
Hi, I am executing this command:
julia extract_ngsim_demonstrations.jl

This is like extremely slow, 1 second per frame for the total of 9500*6 frames. Is it normal?

**Comment by raunakbh92** [comment]
Thanks for the question. We apologize for not updating the branch name. The 0.7fixes branch should work with Julia 1.1 now. Please go ahead and follow the install instructions and they should get you up and running.  

No the `] dev` is not a typo. The `]` key enables you to enter the package mode in the Julia REPL

**Comment by djp42** [comment]
Also, we don't currently offer support for Mac. In the past we have encountered many errors. If you can get it to work, that is great, and please let us know. I will close the issue now since the main question has been answered.
