### ISSUE TITLE
git checkout 0.7fixes_in_progress doesnot work . Does it exist?

### ISSUE THREAD

**Issue by arunsank** [sisl/ngsim_env#16]

**Comment by nebneBgnahZ** [comment]
Hey, I could not find the branch 0.7fixex_in_progress either. How did you solve it?

**Comment by arunsank** [comment]
Yes they have merged it so you can skip the checkout of 0.7

**Comment by nebneBgnahZ** [comment]
Thanks for your quick replay! But I did not see AutoEnvs under ngsim_env/julia, would that be a problem? In addition, some paths (e.g., ngsim_data) are also different according to the install_env_gail_full.md. Thank you:)

**Comment by arunsank** [comment]
Yes setting up is a pain. There were plenty of Julia modifications I did to finally set it up on mine. Answering to your question AutoEnvs is local and should be there if you did it as per the instructions
