### ISSUE TITLE
Distribution difference between Observations and Predicted Actions

### ISSUE THREAD

**Issue by HighlyAuditory** [sisl/ngsim_env#6]
The 'turn_rate_global' feature in the 66-dim observation has max, min, mean approximately 0.05, -0.05, 0.
While I generated some trajectories with PS-GAIL and get the 'mean' action output with statistics max, min, mean as 1.18, -1.36 -0.07.
Why are the two distributions different? Are they with the same units?

**Comment by djp42** [comment]
Can you share more details about how you are calculating these statistics, how many trajectories you are generating, etc? The units should generally be the same, and I can provide more insight if I have more details about what you are doing.

**Comment by HighlyAuditory** [comment]
You were right. The number of my sampled trajs is too small. 
Thank you!

**Comment by djp42** [comment]
Great, glad we resolved it!
